/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.com.github.rerost.todolist_server.api.ListTasksResponse');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.com.github.rerost.todolist_server.api.Task');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.github.rerost.todolist_server.api.ListTasksResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.github.rerost.todolist_server.api.ListTasksResponse.repeatedFields_, null);
};
goog.inherits(proto.com.github.rerost.todolist_server.api.ListTasksResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.github.rerost.todolist_server.api.ListTasksResponse.displayName = 'proto.com.github.rerost.todolist_server.api.ListTasksResponse';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.github.rerost.todolist_server.api.ListTasksResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.github.rerost.todolist_server.api.ListTasksResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.com.github.rerost.todolist_server.api.ListTasksResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.github.rerost.todolist_server.api.ListTasksResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.github.rerost.todolist_server.api.ListTasksResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    tasksList: jspb.Message.toObjectList(msg.getTasksList(),
    proto.com.github.rerost.todolist_server.api.Task.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.github.rerost.todolist_server.api.ListTasksResponse}
 */
proto.com.github.rerost.todolist_server.api.ListTasksResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.github.rerost.todolist_server.api.ListTasksResponse;
  return proto.com.github.rerost.todolist_server.api.ListTasksResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.github.rerost.todolist_server.api.ListTasksResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.github.rerost.todolist_server.api.ListTasksResponse}
 */
proto.com.github.rerost.todolist_server.api.ListTasksResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.github.rerost.todolist_server.api.Task;
      reader.readMessage(value,proto.com.github.rerost.todolist_server.api.Task.deserializeBinaryFromReader);
      msg.addTasks(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.github.rerost.todolist_server.api.ListTasksResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.github.rerost.todolist_server.api.ListTasksResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.github.rerost.todolist_server.api.ListTasksResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.github.rerost.todolist_server.api.ListTasksResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTasksList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.com.github.rerost.todolist_server.api.Task.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Task tasks = 1;
 * @return {!Array<!proto.com.github.rerost.todolist_server.api.Task>}
 */
proto.com.github.rerost.todolist_server.api.ListTasksResponse.prototype.getTasksList = function() {
  return /** @type{!Array<!proto.com.github.rerost.todolist_server.api.Task>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.github.rerost.todolist_server.api.Task, 1));
};


/** @param {!Array<!proto.com.github.rerost.todolist_server.api.Task>} value */
proto.com.github.rerost.todolist_server.api.ListTasksResponse.prototype.setTasksList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.com.github.rerost.todolist_server.api.Task=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.github.rerost.todolist_server.api.Task}
 */
proto.com.github.rerost.todolist_server.api.ListTasksResponse.prototype.addTasks = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.com.github.rerost.todolist_server.api.Task, opt_index);
};


proto.com.github.rerost.todolist_server.api.ListTasksResponse.prototype.clearTasksList = function() {
  this.setTasksList([]);
};


